---
abstract: 'Compare simple hierarchical data'
author:
  - 'Graham Barr'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Difference
requires:
  Test::Differences: 0.50
  Test::More: 0.96
resources:
  repository: git://github.com/gbarr/Data-Difference.git
version: 0.112850
